language: python
python:
- '3.6'
- '3.7'
env: NUMBA_DISABLE_JIT=1
before_install: 
install:
- pip install --upgrade pytest-cov codecov
- python setup.py install
script:
- python -m pytest -vv --log-cli-level=DEBUG  --cov=gbmgeometry/
- codecov --token=655c4d71-b348-4443-917d-73f7e20b2ace
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: KtZLphJh9xIK2wxbv1WCU62nU7hqpSj2wt7Z5zXUt6hMCpiLeF2As4Pc1IkW05t5jxVPj5V0hNDC31FuyoJniZIcAQ9hJ5zFbM8RNOQZMIrjeB6HVgbwOKvHA8c+9ybjHnSARpUA62aZFx1KP+dgI1iKyVMA1bQsRfCQGaG8I5POqUEF0+FN/gu2jKX/gLlmBUbhEivOByrC2GFkTirNYvUUZU8jjsUyjMBs7+s0PsWGjnzgS8uLiDAhQn6K0/PK+q7u7auGCvqg/YyEJcsPquhcIaEX25fVUYixYZylJRp5MIs3AQChsjf5U1OKEZyaj9t2VWiKBP1NIVoi2PZA1K7rkgCUs0mDxBG82XHnlFOXg3d39WSOTSQqLmDfTJ+DfnPxeOXUnT54mbLc4USacsDRUi08s6tWp+VqxH0dlTigb8PRxUBzDCYrZk4NVsmf5mJluO6h0gFssAnIrlXQeJFe1qS3zmCvCD0Kw2raludWFiqx/yBereubRN8P9vtfjw70qN0GtUNPxWrTilUzbK98EP9mb+r6Fm7npd+/2WS5pdiD8PIW610KbU8IntRFtcYlJylpjWe2/KbDaJFs3/p5yrFFjEWHcuch0M49DcMmKSe/wlDe9LxgO9CPh1u0AmPZ72LO/UAqWA17Sknj1BlpYIARIqXAkbRuq2Hb6sc=


    on:
    tags: true
  distributions: "sdist bdist_wheel" # Your distributions here
  skip_existing: true
